// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwdkzspxbhefojmmiltw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3ZGt6c3B4YmhlZm9qbW1pbHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDkzMjcsImV4cCI6MjA2OTc4NTMyN30.2NB9PagCe2D8VfyHxNYsdBIicMx8CwuStS035vWFQXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});